#!/bin/bash

echo "[$(date)] install_callback" >> "/var/log/apps/${TRIM_APPNAME}.log"

if [ -d "${TRIM_APPDEST}/var" ] && [ "$(ls -A "${TRIM_APPDEST}/var" 2>/dev/null)" ]; then
    rsync -avh --ignore-existing --remove-source-files "${TRIM_APPDEST}/var/" "${TRIM_PKGVAR}/"
    rm -rf "${TRIM_APPDEST}/var"
fi

exit 0
