#!/bin/bash

echo "[$(date)] uninstall_callback: wizard_data_action=${wizard_data_action}" >> "/var/log/apps/${TRIM_APPNAME}.log"

if [ "$wizard_data_action" = "delete" ]; then
    echo "[$(date)] User chose to DELETE data" >> "/var/log/apps/${TRIM_APPNAME}.log"

    if [ -d "${TRIM_PKGVAR}" ] && [ "$(ls -A "${TRIM_PKGVAR}" 2>/dev/null)" != "" ]; then
        find "${TRIM_PKGVAR}" -mindepth 1 -delete
    fi

    if [ -d "/var/apps/${TRIM_APPNAME}/etc" ] && [ "$(ls -A "/var/apps/${TRIM_APPNAME}/etc" 2>/dev/null)" != "" ]; then
        find "/var/apps/${TRIM_APPNAME}/etc" -mindepth 1 -delete
    fi
else
    echo "[$(date)] User chose to KEEP data" >> "/var/log/apps/${TRIM_APPNAME}.log"
fi

exit 0
